### ISSUE TITLE
Dockerfile build fails

### ISSUE THREAD

**Issue by naza-fur** [adeyosemanputra/pygoat#159]
=> ERROR [8/9] RUN python3 /app/pygoat/manage.py migrate                                                                                                                                                                          2.3s 
------
 > [8/9] RUN python3 /app/pygoat/manage.py migrate:
#12 2.108 Traceback (most recent call last):
#12 2.108   File "/app/pygoat/manage.py", line 21, in <module>
#12 2.108     main()
#12 2.108     ^^^^^^
#12 2.108   File "/app/pygoat/manage.py", line 17, in main
#12 2.109     execute_from_command_line(sys.argv)
#12 2.110     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.110   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
#12 2.110     utility.execute()
#12 2.110     ^^^^^^^^^^^^^^^^^
#12 2.111   File "/usr/local/lib/python3.11/site-packages/django/core/management/__init__.py", line 440, in execute
#12 2.111     self.fetch_command(subcommand).run_from_argv(self.argv)
#12 2.111     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.112   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 414, in run_from_argv
#12 2.112     self.execute(*args, **cmd_options)
#12 2.112     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.114   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 460, in execute
#12 2.114     output = self.handle(*args, **options)
#12 2.114              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.114   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 98, in wrapped
#12 2.114     res = handle_func(*args, **kwargs)
#12 2.114           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.114   File "/usr/local/lib/python3.11/site-packages/django/core/management/commands/migrate.py", line 91, in handle
#12 2.115     self.check(databases=[database])
#12 2.115     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.115   File "/usr/local/lib/python3.11/site-packages/django/core/management/base.py", line 487, in check
#12 2.115     all_issues = checks.run_checks(
#12 2.115                  ^^^^^^^^^^^^^^^^^^
#12 2.116   File "/usr/local/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
#12 2.116     new_errors = check(app_configs=app_configs, databases=databases)
#12 2.116                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.117   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 42, in check_url_namespaces_unique
#12 2.117     all_namespaces = _load_all_namespaces(resolver)
#12 2.117                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.118   File "/usr/local/lib/python3.11/site-packages/django/core/checks/urls.py", line 61, in _load_all_namespaces
#12 2.118     url_patterns = getattr(resolver, "url_patterns", [])
#12 2.118                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.119   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 49, in __get__
#12 2.119     res = instance.__dict__[self.name] = self.func(instance)
#12 2.119                                          ^^^^^^^^^^^^^^^^^^^
#12 2.119   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 696, in url_patterns
#12 2.120     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
#12 2.120                        ^^^^^^^^^^^^^^^^^^^
#12 2.120   File "/usr/local/lib/python3.11/site-packages/django/utils/functional.py", line 49, in __get__
#12 2.120     res = instance.__dict__[self.name] = self.func(instance)
#12 2.120                                          ^^^^^^^^^^^^^^^^^^^
#12 2.121   File "/usr/local/lib/python3.11/site-packages/django/urls/resolvers.py", line 689, in urlconf_module
#12 2.121     return import_module(self.urlconf_name)
#12 2.121            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.121   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
#12 2.122     return _bootstrap._gcd_import(name[level:], package, level)
#12 2.122            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.122   File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
#12 2.122   File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
#12 2.122   File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
#12 2.122   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
#12 2.122   File "<frozen importlib._bootstrap_external>", line 939, in exec_module
#12 2.123   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
#12 2.123   File "/app/pygoat/pygoat/urls.py", line 18, in <module>
#12 2.123     from introduction import views as v
#12 2.123     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.123   File "/app/pygoat/introduction/views.py", line 32, in <module>
#12 2.124     from PIL import Image,ImageMath
#12 2.124     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.125 ModuleNotFoundError: No module named 'PIL'
------
executor failed running [/bin/sh -c python3 /app/pygoat/manage.py migrate]: exit code: 1

**Comment by adeyosemanputra** [comment]
cc @RupakBiswas-2304

**Comment by adeyosemanputra** [comment]
closed PR #160
