### ISSUE TITLE
Application Error for Live Demos

### ISSUE THREAD

**Issue by gcdeshpande** [adeyosemanputra/pygoat#177]
Hi,

I am trying to access the PyGoat Application live demo using the below three links.
http://pygoat-web.herokuapp.com/
http://pygoat.herokuapp.com/
http://pygoat-dep.herokuapp.com/

But getting application error

**Comment by adeyosemanputra** [comment]
hi @gcdeshpande i suggest you install pygoat in your local machines. we don't maintance these heroku live demo

you can watch pygoat in here
https://youtu.be/RReAi3FJXDk

**Comment by gcdeshpande** [comment]
Hi @adeyosemanputra  Thanks for the update.
