### ISSUE TITLE
Add to VWAD

### ISSUE THREAD

**Issue by kingthorin** [adeyosemanputra/pygoat#40]
You should add the project to VWAD: https://github.com/OWASP/OWASP-VWAD

Also a few other minor notes: your README should have a leading capital on the first sentence. You should remove the .DS_Store file, then add it to your .gitignore (order of operations will matter :wink:)

https://github.com/OWASP/OWASP-VWAD#editing-process

**Comment by adeyosemanputra** [comment]
yes, sure will add it

**Comment by adeyosemanputra** [comment]
thank you @kingthorin
