### ISSUE TITLE
Pygoat on Flask fwk

### ISSUE THREAD

**Issue by dugdug36** [adeyosemanputra/pygoat#6]
Hello, 
When i can expect pygoat on Flask framework ?. In addition can we have write-up vulnerabilities ?

@adeyosemanputra @gaurav618618

**Comment by gaurav618618** [comment]
We are currently very short on contributors will definitely think about that when we have good amount of contributors for sure. Me and @adeyosemanputra are also currently busy with other projects so sorry we cant tell you the exact time period .

**Comment by adeyosemanputra** [comment]
will working and starting now @dugdug36 @gaurav618618

**Comment by adeyosemanputra** [comment]
we done with release V.1.3
