### ISSUE TITLE
More descriptive response in A9

### ISSUE THREAD

**Issue by TMFRook** [adeyosemanputra/pygoat#66]
It would really help if we had a more descriptive response message in A9. When I first saw the result, I wasn't even sure if the payload had worked. 

![image](https://user-images.githubusercontent.com/68116003/129624236-d4380d86-55d6-4980-957b-41f0824eb469.png)

Can we perhaps show the results of the payload? i.e. The contents of the directory if the payload was `ls`?

**Comment by adeyosemanputra** [comment]
@pwned-17 @prince-7
