### ISSUE TITLE
issue with a1 command response

### ISSUE THREAD

**Issue by JustinDPerkins** [adeyosemanputra/pygoat#67]
When performing attack on A1- Command Injection, a error occurs stating no dns utils so command would not run as desired.

Env:
deploy with Fargate

I updated the Dockerfile to add:
# install dependencies
RUN apt-get update
RUN apt-get -y install dnsutils

Now attack displays as your solution for A1: command suggested.
Hope this helps

**Comment by adeyosemanputra** [comment]
hi @JustinDPerkins please submit your PR in here, will review and merge it
