### ISSUE TITLE
Docker image service bound to loopback makes it inaccessible

### ISSUE THREAD

**Issue by XanaDublaKublaConch** [adeyosemanputra/pygoat#72]
I've installed this on a couple of systems to test it out and I was not able to get the Docker image to work without modification. The container starts, but the port is not open inside the container. Docker forwards to the internal network on 8000, but django is only listening on 127.0.0.1, so all connections are rejected. I was able to get it working by changing the CMD in the Dockerfile to use 0.0.0.0 as the listening address and rebuilding.

**Comment by adeyosemanputra** [comment]
i am suggest install by pip3 don't use docker ar this time

**Comment by XanaDublaKublaConch** [comment]
I already got it working in Docker. I was just letting you know the Dockerfile is wrong.

**Comment by adeyosemanputra** [comment]
if you running successfull in docker, please submit PR regarding dockerfile. thank you
