### ISSUE TITLE
A9 not Working due to PyYaml 5.1

### ISSUE THREAD

**Issue by DigvijayBhosale1729** [adeyosemanputra/pygoat#89]
Expected Result - On file upload in A9 Vulnerability, the shell script code inside gets executed and result is shown in the Django Terminal.

Actual Result - On file Upload in A9 vulnerability, this is the error shown due to PyYaml

```
OWASP/pygoat/pygoat/introduction/views.py:465: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  data = yaml.load(file)
```

The Browser shows error as well

![image](https://user-images.githubusercontent.com/70275323/154620778-bc27d1cf-118b-42c1-9483-8a4bcd8b394f.png)

The snippet of code that gives us this error is as follows

```python
try :
    data = yaml.load(file) #Error is due to this line
    return render(request,"Lab/A9/a9_lab.html",{"data":data})
except:
    return render(request, "Lab/A9/a9_lab.html", {"data": "Error"})
```
Probable Cause - PyYaml has made it compulsory to use the `Loader=` while calling yaml.load()

**Comment by adeyosemanputra** [comment]
please help to fix it

**Comment by imraunn** [comment]
#91 I have created a PR fixing this issue
